### ISSUE TITLE
Provide documentation to compile / package

### ISSUE THREAD

**Issue by adericbourg** [KleeGroup/analytica-server#1]
The sources cannot be compiled as is. 

    [ERROR] Failed to execute goal on project kasper-analytica-server: 
        Could not resolve dependencies for project com.kleegroup.analytica:kasper-analytica-server:jar:1.0.0-SNAPSHOT: 
           The following artifacts could not be resolved: 
             com.kleegroup.kasper:kasper-kernel:jar:6.1.17-SNAPSHOT, 
             com.kleegroup.kasper:kasper-kernel:jar:tests:6.1.17-SNAPSHOT: 
               Could not find artifact com.kleegroup.kasper:kasper-kernel:jar:6.1.17-SNAPSHOT -> [Help 1]

**Comment by dslobozian** [comment]
Now in version 1.3.3 Analytica compiles and works.( A simple maven clean install does the job)
